### ISSUE TITLE
planner image loading

### ISSUE THREAD

**Issue by rillstone** [swimuel/ella#41]
#### Description
General loading for the app to make a more seamless experience 

#### Screenshots
![Screen Shot 2019-08-04 at 2 30 58 PM](https://user-images.githubusercontent.com/17172036/62418722-84d66880-b6c4-11e9-9e9e-92245ba12d4a.png)

#### Resources 
- [React-Native-Skeleton-Loader](https://github.com/willikay11/React-Native-Skeleton-Loader)
- [react-native-easy-content-loader](https://github.com/sarmad1995/react-native-easy-content-loader)
- [rn-placeholder](https://github.com/mfrachet/rn-placeholder)
- [rn-svg-loader](https://github.com/virusvn/react-native-svg-animated-linear-gradient)
- [rn-shimmer](https://github.com/tomzaku/react-native-shimmer-placeholder)
- [skeleton](https://reactnativeexample.com/skeleton-placeholder-loader-with-animations/)

#### Expected 
When images do not instantly load, there should be a placeholder to show that something is loading.

#### Tasks
- [ ] planner images
- [ ] Transaction icons

**Comment by swimuel** [comment]
wow these labels are `aesthetic`
